language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_install:
 - chmod +x ./android/gradlew
script:
  - npm run test
  - cd android && TERM=dumb ./gradlew check && cd ..
